batch_size: 4
concept_head_path: ./concept_head_training
concept_identifier: sks
concept_name: cat_statue
concept_type: OBJECT
data_root: ./dataset/data_concept_embedding
device: cuda
head_data_type: hard_negative
learning_rate: 1.0
n_concept_embedding: 1
n_head_negative_samples: 4
n_head_positive_samples: 4
optimization_steps: 100
output_root: ./outputs
personalization_task: VQA
reg_lambda: 10.0
save_interval: 25
seed: 42
threshold: 0.5
torch_dtype: bfloat16
val_interval: 25
vlm_type: LLAVA
