concept_name: concept_name
concept_identifier: sks            # For PERSON, this should be a short name such as Bob or Anna
concept_type: OBJECT               # Can also be PERSON
vlm_type: LLAVA
personalization_task: CAPTIONING   # For LLaVA, we can do either CAPTIONING or VQA
output_root: ./outputs
data_root: ./data
concept_head_path: ./object_concept_heads    # Can be ignored if working with people
threshold: 0.5                               # For PERSON, this should be 0.675
optimization_steps: 100
learning_rate: 1.0
batch_size: 4
reg_lambda: 0.0075
save_interval: 25
val_interval: 25
seed: 42           # If concept is an object, this should be the same seed that was used for training the concept heads
device: cuda
torch_dtype: bfloat16