concept_name: concept_name
concept_identifier: sks            # For PERSON, this should be a short name such as Bob or Anna
concept_type: OBJECT               # Can also be PERSON
vlm_type: LLAVA
personalization_task: VQA   # For LLaVA, we can do either CAPTIONING or VQA
output_root: ./outputs
data_root: ./dataset/data_concept_embedding
concept_head_path: ./concept_head_training    # Can be ignored if working with people
threshold: 0.5                               # For PERSON, this should be 0.675
optimization_steps: 100
learning_rate: 1.0
batch_size: 4
reg_lambda: 10.0
save_interval: 25
val_interval: 25
seed: 1019           # If concept is an object, this should be the same seed that was used for training the concept heads
device: cuda
torch_dtype: bfloat16

n_head_positive_samples: 4
n_head_negative_samples: 4
head_data_type: hard_negative
n_concept_embedding: 1

train_data_type: HEAD # or RANDOM (random is random choice, head is train data that is concept_head training data and same about test data)